TrajectoryPlannerROS:
	max_vel_x: 0.2
	min_vel_x: 0.1
	max_vel_theta: 0.4
	min_in_place_vel_theta: 0.2

	acc_lim_theta: 2.0
	acc_lim_x: 0.5
	acc_lim_y: 0.5	

	yaw_goal_tolerance: 1
	xy_goal_tolerance: 0.02
	latch_xy_goal_tolerance: false

	holonomic_robot: false
	meter_scoring: false
