footprint: [[0.20,0.16], [-0.12, 0.16], [-0.12, -0.16], [0.20,-0.16]]

resolution: 0.05

#range_sensor_layer:
#  clear_threshold: 0.5
#  mark_threshold: 1.0
#  inflated_cone: 0.0
#  clear_on_max_reading: false
#  frame: sonar_link
#  topics: ["/sonar"]

#inflation_layer:
#  inflation_radius: 0.1
#  cost_scalling_factor: 3

#obstacle_layer:
#  obstacle_range: 1.0
#  raytrace_range: 1.5
#  observational_sources: scan
#  observation_persistence: 0.0
#  scan:
#    data_type: LaserScan
#    topic: scan
#    marking: true
#    clearing: true
