global_costmap:
  global_frame: map
  robot_base_frame: base_link
  width: 10.0
  height: 10.0
  origin_x: 5.0
  origin_y: 5.0  
  update_frequency: 2.0

  #plugins:
   # - {name: range_sensor_layer, type: "range_sensor_layer::RangeSensorLayer"}
   # - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   # - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
   # - {name: static_layer, type: "costmap_2d::StaticLayer"}
