local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 2.0
  rolling_window: true
 

  #plugins:
   # - {name: range_sensor_layer, type: "range_sensor_layer::RangeSensorLayer"}
   # - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   # - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

